// <auto-generated />
using System;
using HouseRentingSystemApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HouseRentingSystemApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401092254_SeedAdded")]
    partial class SeedAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HouseRentingSystemApi.Data.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HouseRentingSystemApi.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Name = "SingleBedroom"
                        });
                });

            modelBuilder.Entity("HouseRentingSystemApi.Data.Entities.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Address = "15 Vitosha Blvd, Sofia",
                            CategoryId = 1,
                            Description = "Bright and modern apartment located in the heart of Sofia, close to restaurants and metro.",
                            ImageUrl = "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
                            PricePerMonth = 950m,
                            Title = "Modern Apartment in Sofia Center",
                            UserId = "df26734f-abc3-4aba-b5de-bea3da51c483"
                        },
                        new
                        {
                            Id = 5,
                            Address = "22 Borisova Gradina, Sofia",
                            CategoryId = 2,
                            Description = "Small but cozy studio next to the park, ideal for students or young professionals.",
                            ImageUrl = "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
                            PricePerMonth = 600m,
                            Title = "Cozy Studio near Park",
                            UserId = "df26734f-abc3-4aba-b5de-bea3da51c483"
                        },
                        new
                        {
                            Id = 6,
                            Address = "8 Cherni Vrah Blvd, Sofia",
                            CategoryId = 3,
                            Description = "Spacious penthouse with panoramic city views and modern interior.",
                            ImageUrl = "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
                            PricePerMonth = 1800m,
                            Title = "Luxury Penthouse with View",
                            UserId = "df26734f-abc3-4aba-b5de-bea3da51c483"
                        },
                        new
                        {
                            Id = 7,
                            Address = "5 Oak Street, Bankya",
                            CategoryId = 1,
                            Description = "Quiet family house with garden, perfect for long-term living.",
                            ImageUrl = "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
                            PricePerMonth = 1200m,
                            Title = "Family House in Suburbs",
                            UserId = "df26734f-abc3-4aba-b5de-bea3da51c483"
                        },
                        new
                        {
                            Id = 8,
                            Address = "45 Bulgaria Blvd, Sofia",
                            CategoryId = 2,
                            Description = "Clean and minimalist apartment with all necessary amenities.",
                            ImageUrl = "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
                            PricePerMonth = 800m,
                            Title = "Minimalist Apartment",
                            UserId = "df26734f-abc3-4aba-b5de-bea3da51c483"
                        },
                        new
                        {
                            Id = 9,
                            Address = "10 Coastal Road, Varna",
                            CategoryId = 3,
                            Description = "Beautiful apartment with sea view, just minutes from the beach.",
                            ImageUrl = "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
                            PricePerMonth = 1100m,
                            Title = "Sea View Apartment",
                            UserId = "df26734f-abc3-4aba-b5de-bea3da51c483"
                        },
                        new
                        {
                            Id = 10,
                            Address = "12 Kapana District, Plovdiv",
                            CategoryId = 2,
                            Description = "Compact studio in the artistic Kapana district.",
                            ImageUrl = "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5",
                            PricePerMonth = 550m,
                            Title = "Compact Studio in Plovdiv",
                            UserId = "df26734f-abc3-4aba-b5de-bea3da51c483"
                        },
                        new
                        {
                            Id = 11,
                            Address = "7 Green Hill, Sofia",
                            CategoryId = 1,
                            Description = "Large house with private garden and garage.",
                            ImageUrl = "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
                            PricePerMonth = 1500m,
                            Title = "Spacious House with Garden",
                            UserId = "df26734f-abc3-4aba-b5de-bea3da51c483"
                        },
                        new
                        {
                            Id = 12,
                            Address = "33 Industrial Zone, Sofia",
                            CategoryId = 3,
                            Description = "Stylish loft with open space design and high ceilings.",
                            ImageUrl = "https://images.unsplash.com/photo-1484154218962-a197022b5858",
                            PricePerMonth = 1000m,
                            Title = "Modern Loft",
                            UserId = "df26734f-abc3-4aba-b5de-bea3da51c483"
                        },
                        new
                        {
                            Id = 13,
                            Address = "18 Studentski Grad, Sofia",
                            CategoryId = 2,
                            Description = "Affordable room suitable for students.",
                            ImageUrl = "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
                            PricePerMonth = 400m,
                            Title = "Budget Room",
                            UserId = "df26734f-abc3-4aba-b5de-bea3da51c483"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HouseRentingSystemApi.Data.Entities.House", b =>
                {
                    b.HasOne("HouseRentingSystemApi.Data.Entities.Category", "Category")
                        .WithMany("Hosues")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseRentingSystemApi.Data.Entities.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HouseRentingSystemApi.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HouseRentingSystemApi.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseRentingSystemApi.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HouseRentingSystemApi.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HouseRentingSystemApi.Data.Entities.Category", b =>
                {
                    b.Navigation("Hosues");
                });
#pragma warning restore 612, 618
        }
    }
}
